### ISSUE TITLE
Set up Netlify deploy

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/teaching-portal#3]
@garrettdashnelson will do this.

To @alexandergknoll - for now I'll assume that we'll just deploy the `main` branch directly to Netlify. In the future, once we get closer to completion, let's talk about different options for whether we want to create something like a `staging` branch. However, for the time being I am comfortable with committing directly to `main` without any PRs or review process.

**Comment by alexandergknoll** [comment]
@garrettdashnelson not sure if you wanted to own everything related to netlify, but in case you would like me to have access to that my Netlify account email is netlify@agk.io - thanks!

**Comment by garrettdashnelson** [comment]
@alexandergknoll I've still been trying to figure out how to make Netlify cost-effective when multiple contributors are part of a team, so for the time being, unless I need any help, I'll try to handle the Netlify deploy stuff!

**Comment by garrettdashnelson** [comment]
OK, set this up so that it is wired to https://lmec-teaching-portal-dev.netlify.app and watching `main` for changes.

I will add this into the README and close this issue as complete for now.
