### ISSUE TITLE
Create skeleton `/` landing page

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/teaching-portal#4]
@garrettdashnelson will provide a visual sketch of some extremely simple ideas for this

**Comment by garrettdashnelson** [comment]
![root page](https://github.com/bplmaps/teaching-portal/assets/2424901/4e17890f-ebe0-4733-a833-6a9735bfc3b7)

**Comment by alexandergknoll** [comment]
@garrettdashnelson looks good!  The only suggestion I might make is to skip the carousel on the lesson plan cards and just display in a paginated grid.  With an increasing amount of content we should add categories and search for easier discovery, but in my experience the carousels are a bit clunky to navigate.  But if we do go with a carousel I would recommend [Swiper JS](https://swiperjs.com/).

Proposed components for starting point with Tailwind UI:

- Header: ["With-call-to-action"](https://tailwindui.com/components/marketing/elements/headers#component-ee5df49936fc6550a95895277c81f43c)
- Cards: ["Three-column with background image"](https://tailwindui.com/components/marketing/sections/blog-sections#component-7c4bcd0e50e14e855d55d20b6cd445d1)
- Footer: "[Simple centered](https://tailwindui.com/components/marketing/sections/footers#component-8fd8a490ec2fae888154eb83685bbe23)"

**Comment by garrettdashnelson** [comment]
@alexandergknoll Agreed, let's ditch the carousel for now. Can just show a maximum of three cards and perhaps a "More featured lesson plans" link. And 👍 to all those proposed Tailwind UI elements.

**Comment by alexandergknoll** [comment]
I went ahead and implemented this at a basic level for now.  We can definitely give it some more polish and personality later.  One other outstanding thing would be to add the javascript needed to make the mobile navigation functional

**Comment by garrettdashnelson** [comment]
I think if we implement the JS for popping/unpopping the menu, then we can call this one closed.

**Comment by alexandergknoll** [comment]
Added this with 4ad41e2 - closing this one out!
