### ISSUE TITLE
Title/Name duplicative fields

### ISSUE THREAD

**Issue by alexandergknoll** [bplmaps/teaching-portal#6]
@garrettdashnelson just going to add a few notes here occasionally when I stumble on things - hope you don't mind!

I noticed that there's a field for both "Name" and "Title" for the lesson plan stories.  Should we combine these or are they meant to be distinct?  In the one example currently in Story Blok the values for these are "Example Lesson Plan" and "The story of the Bonner map" respectively.

**Comment by garrettdashnelson** [comment]
Ah, I didn't even notice that "Name" is a default required Storyblok field, and that it also seems to populate the slug by default (unless it is changed manually). Why don't we toss out "Title" and simply use "Name" for that purpose.

**Comment by alexandergknoll** [comment]
Solved by bb705fa
